version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  go:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run cmd/server/main.go"
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app