CREATE TABLE mountains (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    reading_name VARCHAR(255) NOT NULL,
    image_path VARCHAR(255) NOT NULL,
    short_description TEXT NOT NULL,
    long_description TEXT,
    elevation INT NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    region VARCHAR(100) NOT NULL,
    prefectures VARCHAR(255) NOT NULL,
    is_climbed BOOLEAN DEFAULT FALSE NOT NULL,
	schedule VARCHAR(255)  NOT NULL,
	best_season VARCHAR(255)  NOT NULL,
	physical_strength INT  NOT NULL,
	difficulty INT  NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;